from common.const import MISSILE_LAUNCHER, LASER_TURRET, MINI_GUN, SHIELD_REPAIRER, HULL_REPAIRER

loot_types = [
    MISSILE_LAUNCHER,
    LASER_TURRET,
    MINI_GUN,
    SHIELD_REPAIRER,
    HULL_REPAIRER,
]
